### PR TITLE
Add lot of functions to API

### PR DESCRIPTION
**Pull request by Virinas-code**
Check out berserk/todo.md

### CODE REVIEW

**Comment by rhgrant10** [comment]
wow thank you @Virinas-code! this is fantastic. would you mind rebasing? I've migrated off of travis-ci and replaced it with a github action that _should_ trigger on this PR when you rebase. if you can resolve any test/lint issues that come up I can get this merged and cut a new release

**Comment by Virinas-code** [comment]
OK! Thank you for supporting this PR! I will update this after 1 or 2 days, I have a lot of work. Thank you!

**Comment by Virinas-code** [comment]
Ready to merge.

**Comment by rhgrant10** [comment]
@Virinas-code I didn't know I had to approve the github action workflow to run on this PR, but I've done that now 👍  Thanks for rebasing - the new workflow checks show it builds and the tests pass (I'm not worried about the codecov one for now btw)

Couple of things still needed here:
- please fix the pep8 errors according to the flake8 check (you can check locally with `tox -e flake8`)
- please switch the quotes back to single 😄

**Comment by Virinas-code** [comment]
Hmm... Why are you using SINGLE quotes?

**Comment by Virinas-code** [comment]
OK, all problems fixed.

**Pull request merged**
