### PR TITLE
add board api

### PR DESCRIPTION
**Pull request by haklein**
This PR adds the new board API calls

### CODE REVIEW

**Comment by rhgrant10** [comment]
Hey looks good, thank you. I'll merge this for the next release. Hopefully this weekend :smiley:

**Comment by haklein** [comment]
> Hey looks good, thank you. I'll merge this for the next release.
> Hopefully this weekend 😃
> 

great, thanks!

**Comment by haklein** [comment]
@rhgrant10 is the PR good to go or do I need to rework it?

**Comment by haklein** [comment]
@rhgrant10 sorry to nag, but this would be essential for the new lichess board api. May I kindly ask to merge this?

**Comment by rhgrant10** [comment]
Hot off the press, [v0.8.0](https://pypi.org/project/berserk/0.8.0/)

**Comment by haklein** [comment]
thanks a lot!!

**Pull request merged**
